---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: whoami
  labels: 
    app: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: traefik/whoami
        ports: 
        - name: web
          containerPort: 80
      imagePullSecrets:
        - name: docker-hub-auth
      #nodeSelector:
      #  kubernetes.io/hostname: rockpi12
---
kind: Service
apiVersion: v1
metadata:
  name: whoami
spec:
  ports:
  - protocol: TCP
    port: 80
    name: web
  selector:
    app: whoami
