# File: ./overlays/prod/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

images:
- name: traefik/whoami
  newName: docker-io.nas.fischbacher.rocks/traefik/whoami
  newTag: v1.6.1

resources:
  - ../../bases/
  - ingressroute.yaml
