# File: ./overlays/prod/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-test

images:
- name: traefik/whoami
  newName: dockerhub-proxy.kube.fischbacher.rocks/traefik/whoami
  newTag: v1.6.1

resources:
  - ../../bases/
  - ingressroute.yaml
